checkpoint:
  path: /mount/arbeitsdaten54/projekte/deepfake/SpeechTechnology2023/chihyi/deepfake-whisper-features/trained_models/model__whisper_frontend_mesonet__2024-04-08_09-41-10/ckpt.pth
data:
  seed: 42
loss_model_checkpoint:
  path: /mount/arbeitsdaten54/projekte/deepfake/SpeechTechnology2023/chihyi/deepfake-whisper-features/trained_models/model__whisper_frontend_mesonet__2024-04-08_09-41-10/ocsoftmax_ckpt.pth
model:
  name: whisper_frontend_mesonet
  optimizer:
    lr: 1.0e-06
    weight_decay: 0.0001
  parameters:
    fc1_dim: 1024
    freeze_encoder: false
    frontend_algorithm:
    - mfcc
    input_channels: 2
